-- AlterTable
ALTER TABLE "Coach" ADD COLUMN     "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "modifiedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "statusChangeDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
